//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace token_auth_example.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo_table
    {
        public int id { get; set; }
        public string usrname { get; set; }
        public string password { get; set; }
        public string authtoken { get; set; }
        public Nullable<System.DateTime> issued_on { get; set; }
        public Nullable<System.DateTime> expired_on { get; set; }
    }
}
